### ISSUE TITLE
Add support for current packages in web UI

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/cluster-mgr#10]
When configuring provider nodes in web UI and selecting "Gluu server" mode, only "3.0.1" version is available in dropdown list. Support for all current packages should be added before releasing it. This rises a question of whether we need to spend efforts on adding support for 3.0.2 if 3.1.0 is planned to be released in August? We could aim cluster manager's release to August as well, and concentrate on support for just package 3.1 and newer. 3.0.1 support should be removed on release (I believe cluster manager is used only with newly installed servers, so no reason to support outdated packages in it; please correct me otherwise)

**Comment by willow9886** [comment]
@iromli @shouro this is a high priority. We need to support CE 3.0.2
