### ISSUE TITLE
Email notifications for license expiration

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cluster-mgr#101]
We should send email notifications to cluster manager admin users when their license is getting ready to expire. 

Email notification should be sent:

- 90 days before expiration
- 60 days before expiration
- 30 days before expiration
- 0 days before expiration (notifying users that their license is expired, and they need to renew in order to regain access).

Chris or I can provide content as needed.

**Comment by iromli** [comment]
@willow9886 who shall receive the email? Admin of cluster-manager?

**Comment by willow9886** [comment]
@iromli yes, correct. It should go to admin users

**Comment by willow9886** [comment]
Hi {First_name},

Your Gluu enterprise license is set to expire in `#` days. 

If you have already renewed your Gluu support contract, you can ignore this message. 

Otherwise please email sales@gluu.org to initiate your organization's support renewal.

Thank you!

Gluu, Inc.

**Comment by iromli** [comment]
thanks @willow9886

**Comment by iromli** [comment]
Merged to `2.1` branch.
