### ISSUE TITLE
During license enforcement, check`product_parameter`

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cluster-mgr#102]
During license enforcement, we must confirm that the license's product parameter includes `cluster_manager`.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/oxLicense/issues/19

cluster_manager is a product parameter as of now. Does Cluster Manager check for license parameters @iromli ? I think I see it here:

https://github.com/GluuFederation/cluster-mgr/blob/8ee44405957f63b2eb3c11b36a5962d92343e5c3/clustermgr/core/license.py#L62

We should change this to "cluster_manager"

**Comment by iromli** [comment]
The product parameter modification has been applied in `master` branch.

![screenshot from 2018-01-06 09 49 12](https://user-images.githubusercontent.com/231601/34635828-f51453c6-f28c-11e7-9acb-60d27586fdae.png)
