### ISSUE TITLE
Catch DEBCONF stderr error

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#104]
![image](https://user-images.githubusercontent.com/30447907/33951643-273af85a-dff5-11e7-94ed-9d53dc90fbd6.png)

Everything seems to work regardless, but this error causes a "retry" attempt.

**Comment by mbaser** [comment]
We should switch to ntp rather than ntpupdate. One make one of the servers as ntp server (preferable primary server) and make other as ntp client for that server for a smooth time sync.
