### ISSUE TITLE
Detection of Gluu-Server installation and OS

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#106]
I have two VMs; one has Gluu CE installed and another one has openLDAP for Gluu Server [ Gluu Server installation with remote openldap ]. 

Tried to add that first VM ( which has CE installed ) in cluster-mgr but it couldn't detect installed CE and OS. 
When I hit 'Install Gluu Server' button; cluster-mgr uninstalled my CE and installed a new CE there. 

I am exactly not sure how cluster-mgr detect an 'installed CE version' but most probably that need some improvement when we have some CE installed whose bits ( oxAuth,oxTrust, LDAP etc. ) are scattered among multiple VMs.

**Comment by mbaser** [comment]
This what I dreamed at the beginning: adding already installed gluu server to cluster. Unfortunately, I can't make gluu ui work after changing hostname.

**Comment by mbaser** [comment]
See the closed issue:
https://github.com/GluuFederation/cluster-mgr/issues/24

**Comment by tecoholic** [comment]
> adding already installed gluu server to cluster

Aren't we adding existing gluu-server as the primary server?

**Comment by mbaser** [comment]
No, we aren't. It can't be possible. the host of existing gluu-server should be nginx host. For eaxmple if you have existing gluu server on host auth.mydomain.org, and if you want to have two gluu in cluster as auth1.mydomain.org and auth2.mydomain.org, then you should install nginx on host auth.mydomain.org and change all hostname definitions on gluu server to auth1.mydomain.org

**Comment by afroDC** [comment]
As it stands currently, if you add a server to Cluster Manager, after some time, it will detect if Gluu is installed along with the OS.

For example, you can add all previously configured clusters to Cluster Manager and it will work as expected.

We are currently working on taking the stand-alone data of Gluu and preparing and sanitizing the information for a cluster configuration. I will create another ticket for that.
