### ISSUE TITLE
Print Gluu Support License on setup/start-up

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#107]
We should print the [Gluu Support](https://raw.githubusercontent.com/GluuFederation/gluu-gateway/master/LICENSE) license and ask the user:

Do you acknowledge that use of the Gluu Gateway is under the GLUU-SUPPORT license? [y|N]: 

Defaults to not accepting the license.

**Comment by iromli** [comment]
Merged to `master` branch.
