### ISSUE TITLE
File system replication among all nodes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#108]
Though most of the configurations are there inside LDAP and syncing of those configurations are covered with ldap replication but we need to sync some files among all nodes of the cluster. 

We need to add a file system replication mechanism in cluster. 

In our 2.4.4, we used to use Csync2 which syncs 'listed directories' across all nodes of a cluster. It trust node based on cert+key and run in root cronjob from inside container. 

Feel free to check GlusterFS / Lustre ( http://wiki.lustre.org/index.php/Main_Page ) / Ceph ( http://ceph.com/ ) / OpenAFS ( http://openafs.org/ ) / Apache Helix ( https://helix.apache.org/ ) or whatever is easier but stable + secure for our cluster-mgr setup. 

Here are primary listed directories which we need to sync: 

-  /opt/gluu/jetty/identity/conf/shibboleth3/idp/
- /opt/gluu/jetty/identity/conf/shibboleth3/sp/
- /opt/shibboleth-idp/conf
- /opt/shibboleth-idp/metadata/
- /opt/shibboleth-idp/sp/
- /opt/shibboleth-idp/temp_metadata/
- /etc/gluu/conf/
- /etc/certs/
- /opt/symas/etc/openldap/
- /opt/opendj/

**Comment by afroDC** [comment]
`I think we should separate filesystem replication from ldap replication.
And we need to enable admin to  include directories to be synced and actions`

`In that case, let's have a "Replication" drop down menu where it shows "LDAP" and then also "File System"`
