### ISSUE TITLE
Gluu-OpenDJ Support

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#109]
CE now supports OpenDJ again. We should add support to cluster manager for OpenDJ too.

**Comment by afroDC** [comment]
Broken into 3 parts.

https://github.com/GluuFederation/cluster-mgr/issues/111

https://github.com/GluuFederation/cluster-mgr/issues/112

https://github.com/GluuFederation/cluster-mgr/issues/113
