### ISSUE TITLE
Case when 2nd (mirror) node couldn't be configured should be handled in more user friendly way

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/cluster-mgr#11]
Just bumped into it by accident when configuring cluster setup with 2 providers. In case attempt to add a mirroring server is failed (i.e. there was an error after you clicked "Setup server" button for the 2nd (mirror) server for any reason (in my case ssh pub key was not added to the 2nd node)) web UI ends in a bit confusing state. You can see both servers on "Dashboard" page, but there are no obvious ways to restart the whole process. I figured out you need to remove both server there, but it took some time, and I wasn't perfectly sure it's a correct way to proceed. For now, I'll describe this case in docs, but web UI should be more straightforward here, IMO. 2 option are:

1. [Easier to implement] In case setup of 2nd server failed, the whole process of setting up servers is deemed as failed, nothing is displayed at "Dashboard" page and user is taken back to page where the 1st server is set up
2. [More user-friendly]  In case setup of 2nd server failed and error is displayed, you are proposed to retry starting with the 2nd server right away

**Comment by aliaksander-samuseu** [comment]
@iromli 

I see that docs do mention case when some consumer misbehaves or wasn't properly configured, and recommend to remove it and re-add again with "Add consumer" button. But we don't have such controls for a 2nd Provider node for a mirrored setup I'm referring to. So we need to add something like that.

**Comment by tecoholic** [comment]
1. When something bad happens and an error is thrown, something like this is shown.
![gluu_cluster_manager](https://user-images.githubusercontent.com/383862/28153528-7e6211cc-67c3-11e7-850b-ff9366a091c7.png)

2. The dashboard does end in a confused state, because both the servers are shown. I will roll out a fix for this confused state of the dashboard.

**Comment by tecoholic** [comment]
Closing this, as we no longer are doing mirror-mode specific config.
