### ISSUE TITLE
Breaking apart oxTrust, oxAuth and LDAP

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#115]
`
We also need to allow modularity in the topology of deployments. Say I want to install redis on my proxy server and n2, oxAuth/oxTrust installed on n1-3, OpenLDAP installed on n1-2. This would involve some custom configuration of files in /etc/default/ and the apache configuration, but is possible.
`

To do this algorithmic-ally, I believe it will be necessary to modify the following files:

```
/etc/gluu/conf/ox-ldap.properties (To point to all the LDAP servers)

/etc/default/oxauth (Might not be necessary)

/etc/default/identity (Might not be necessary)

...

/etc/apache2/sites-available/https-gluu.conf (Here you can change the routing to point back to the proxy server, if it's not localhost, to connect it to the proper server, with the correct service..)
```
  
More information to follow..

**Comment by shmorri** [comment]
This feature will be available in Enterprise Edition, rather than Cluster Manager.
