### ISSUE TITLE
Robust Replication Method Not Requiring Server Restart

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#116]
`
We also need to figure out a more robust way of adding nodes to the LDAP cluster that doesn't involve taking the active systems offline. It will require further research.
`
I don't think this is an issue with OpenDJ, but with OpenLDAP you have to restart the whole server.

Must do further testing to figure out proper method.

**Comment by mbaser** [comment]
closed with e160ccb
