### ISSUE TITLE
It will be better if the "Configuring Gluu CE for Replication" document section reminds of ssh issues

### ISSUE THREAD

**Issue by James-ZHANG** [GluuFederation/cluster-mgr#12]
Currently in the "Configuring Gluu CE for Replication" document section (https://gluu.org/docs/cm/alpha/configuration/configuring-GluuCE-Cluster/), the instruction does not mention about adding clustermgr's ssh public key to server2's ./.ssh/authorized_keys. Although this has already been mentioned in "Install Cluster Manager" section, I think it will be better to re-emphasize that again since most users will simply follow the six steps in the Home section (https://gluu.org/docs/cm/alpha/) and they might well forget the ssh issues after so many configuration steps:)

**Comment by willow9886** [comment]
@iromli can you update this?

**Comment by iromli** [comment]
@willow9886 sure

**Comment by iromli** [comment]
Updated in https://github.com/GluuFederation/docs-clustermgr-prod/commit/45b1cd0d516d70721fc7f34817757c78527d7295 revision. Online docs should be updated soon.
