### ISSUE TITLE
SCIM consistency

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#126]
Setup.py creates a file in /install/community-edition-setup/output/ called scim-rp,jks which is associated with oxAuthJwks in `inum=@!<inum>!0001!<inum>!0008!<inum>,ou=clients,o=@!<inum>!0001!<inum>,o=gluu`. 

So the problem comes when we run setup.py multiple times which results in there being multiple scim-rp's with only the primary servers scim-rp.jks being accurate (I think) with the corresponding key in oxAuthJwks. 

I'm wondering if we have a way to deal with this conundrum. Looking for feedback and solutions.

**Comment by mbaser** [comment]
`setup.py` should be run only once on a server. How do you run multiple times?

**Comment by afroDC** [comment]
On time on multiple machines @mbaser.

**Comment by mbaser** [comment]
This is not relevant for recent Cluster Manager. Clustermgr executes `setup.py` with argument `--no-data` on secondary servers, and that prevents importing data to LDAP. We let all data replicated from primary server. Additionally `scim-rp.jks` is copied from primary server to secondaries.
