### ISSUE TITLE
Hostname IP Discrepancy in Logging

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#128]
While looking through the logging function, I noticed that the same hostname has the same IP addresss. For example:

![image](https://user-images.githubusercontent.com/30447907/35419433-89bc9d2e-01fd-11e8-833a-6c2d0a8b46b9.png)

I believe this is due to the way Gluu installations impact Ubuntu's hostname. We should used the Hostnames in the DB correlated with the IP address if possible:

![image](https://user-images.githubusercontent.com/30447907/35419455-a3e31dae-01fd-11e8-85d0-568dd3caeaa6.png)

**Comment by iromli** [comment]
> I believe this is due to the way Gluu installations impact Ubuntu's hostname. We should used the Hostnames in the DB correlated with the IP address if possible:

Yes, unfortunately all servers use same hostname. We can pass the server info while saving logs.

**Comment by iromli** [comment]
Patches merged to `master` branch
