### ISSUE TITLE
Incorrect filebeat templates for HTTPD and Redis logs in CentOS

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cluster-mgr#136]
HTTPD and Redis logs are not collected by filebeat due to incorrect paths and patterns.

**Comment by iromli** [comment]
Patches merged to master branch

**Comment by afroDC** [comment]
Fixed https://github.com/GluuFederation/cluster-mgr/commit/02fae56641511b3cf56a159a4f3dbfb09af392b0
