### ISSUE TITLE
Add an option to use IP Address to connect to Hosts

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#14]
The cluster manager uses the hostname entered during the time of server setup for all its connections and communication. Adding an option to use the the IP instead of hostname could add flexibility to the configuration, maybe even be useful for single hostname-multiple IP/servers setup.

**Comment by afroDC** [comment]
Can you use an IP address in the syncrepl settings for OpenLDAP? Isn't that what the hostname is used for?

**Comment by mbaser** [comment]
Program first try to connect with hostname if, successfull all remaining uses hostname, if it was not, it tries ip address. Ok I will put ip address as an option.

**Comment by tecoholic** [comment]
@afroDC I think using ip address in syncrepl would cause the tls_cert check to fail as the CN would be the hostname. If all the instances are going to have the same hostname, we might be getting into some sort of a problem here.

**Comment by afroDC** [comment]
So all servers inside syncrepl refer to the other LDAP servers FQDN. The LDAP process communicates directly with the other LDAP servers with no proxy intervention and hasn't had any trouble so far.

**Comment by mbaser** [comment]
We disabled server certificate checking on replication process. Self signed certificates does not work with syymas-openldap, athgough it works with openldap on debian based distributions.

Sent: Tuesday, September 26, 2017 at 8:10 PM

**Comment by afroDC** [comment]
Ah yes, I'm thinking of httpd certs. If that's the case, I don't think there will be any issue.
