### ISSUE TITLE
Manage oxAuth Key Rotation

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cluster-mgr#143]
`clustermgr` needs to handle key rotation feature (revisit disabled feature).

Things to consider:
- use JKS backend only to store public keys
- user able to enable/disable key rotation
- user able to customize how key rotation should run (for example, when keys should be rotated)

**Comment by nynymike** [comment]
In a one server deployment, key regeneration can be handled by oxAuth

![image](https://user-images.githubusercontent.com/3717101/36276696-5cae285e-1254-11e8-88aa-ea0246a8bf00.png)

But in a cluster, this is a clunky process.  

It would probably be best if cluster manager generates the keys and makes available to oxAuth servers

**Comment by iromli** [comment]
Cluster manager will set `keyRegenerationEnabled` to false (as seen here https://github.com/GluuFederation/cluster-mgr/blob/master/clustermgr/tasks/keyrotation.py#L102).

After generating keys, cluster manager will update private keys in the LDAP entry and distribute the `oxauth-keys.jks` to all servers.
