### ISSUE TITLE
DOC: Add diagram for required ports

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#148]
Something like below: 

![port_opening_cluster_mgr](https://user-images.githubusercontent.com/7156097/36481865-c99f3d46-16d6-11e8-9726-9f218c7e0f66.jpg)

**Comment by afroDC** [comment]
Will review this and put it into the documentation.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/docs-clustermgr-prod/commit/b8b9c1230b5c1b0e309aa1d5423b8739ad4fcf3a
