### ISSUE TITLE
DOC: Add example for 'auth.ini' code

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#149]
What to write in 'auth.ini' file? 
Some example would be great in doc.

**Comment by mbaser** [comment]
You don't have to write anything to `auth.ini` It is created by clustermgr

**Comment by afroDC** [comment]
@mbaser is right. You just need to log in initially and it will create the file for you. Maybe an example of what one looks like might be ideal.

**Comment by mbaser** [comment]
auth.ini is created by clustermgr, closing this issue.
