### ISSUE TITLE
DOC: 'Fetch Cache Method'

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#153]
What is that actually? Why do we need that? Is that mandatory? -- these can be added in Doc.

**Comment by afroDC** [comment]
Okay I'll update the docs.

For reference, the "Fetch cache method" will tell you whether your cluster is properly configured with Redis or if it still uses `IN_MEMORY`, which will make the cluster not function properly.

**Comment by afroDC** [comment]
Fixed with https://github.com/GluuFederation/docs-clustermgr-prod/commit/43ca3d8dab77b0c033993bb6fcaa6ea86e6331ff
