### ISSUE TITLE
'LDAP Replication' consistency checking

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#156]
Sometimes the GUI and backend is not syncing. Screenshot attached: 'replication status.png'. See in backend.. we can observe that both servers are replicating but in GUI it's showing just one server in replication pool.

![replication_status](https://user-images.githubusercontent.com/7156097/36482250-4bae056e-16d8-11e8-8765-2a3c2531fffc.png)

**Comment by afroDC** [comment]
We had an issue we fixed in the latest build, since we don’t restart openDJ anymore. The problem here was that the server hadn’t fully restarted. You can see it where it says Connection refused and immediately after check the `LDAP Replication` screen and it will show your replication status.
