### ISSUE TITLE
'Dry run' feature

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#157]
Possible to add some 'Dry Run' feature? Like which will check ports, SSH connectivity, hostname accessibility of all components of any cluster setup before even starting installation? Also if possible... add something like 'Check Status' which will check all those points 'AFTER' the completion of installation?

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/37052974-90345d56-2140-11e8-91e3-e46b6ac42a62.png)

Current Status should show that the services on c2.gluu.org are active, as it's currently fully functioning as a Gluu server, but they're showing as inactive, although reachable from the load balancer. I'm not sure why they're not showing as green checks.
