### ISSUE TITLE
'LDAP Status' is not right

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#158]
check out the screenshot please. 
Server 2: LDAP Status is 'Down' but it's 'UP' actually . 
![ldap_status_not_right](https://user-images.githubusercontent.com/7156097/36631397-c4a61c48-193c-11e8-8e91-93dc12aacb62.png)

**Comment by afroDC** [comment]
I believe this is related to a server that might have been down but came up between the default 5 minute LDAP status polling configured in `Settings`

**Comment by mbaser** [comment]
I never saw this before.

**Comment by mzico** [comment]
@mbaser, I got some info from @afroDC which I am going to recheck to double check this situation.

**Comment by mbaser** [comment]
Zico, could we close this issue, I still did not see this.

**Comment by mzico** [comment]
@mbaser : Please close it.

**Comment by afroDC** [comment]
Cannot replicate issue. Closed until we can repeat.
