### ISSUE TITLE
file system replication issue in AWS 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#176]
Our standard file system replication ( aka. csync2 replication ) doesn't work with AWS instances. One and only reason is: Amazon's strange type of networking. 

Here are points we need to check before configuring csync2 in AWS: 

 - We need to configure csync2 inside host ( not inside container ) because csync2 is highly dependent on hostname and AWS instances can't talk to each other with fake hostnames. 
 - We can't use internal ip address to configure csync2 because this piece of software can't work with IP address. 

Below points can be considered to automate csync2 configuration: 

- `/etc/hosts` file: it must have mapping like below: 

```
[root@ip-11-22-33-4444 ~]# cat /etc/hosts
#127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
#::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
11.22.33.444         ip-11-22-33-444.ec2.internal 
11.55.66.777         ip-11-55-66-777.ec2.internal
```
- `server_args` of csync2 of xinetd.d can't have hostname specified. Configuration should be something like this: 

```
# default: off
# description: csync2
service csync2
{
        flags           = REUSE
        socket_type     = stream
        wait            = no
        user            = root
        group           = root
        server          = /usr/local/sbin/csync2
        server_args     = -i -l
        port            = 30865
        type            = UNLISTED
        # log_on_failure += USERID
        disable         = no
        # only_from     = 192.168.199.3 192.168.199.4
}
```
- cronjob can't have hostname specified, such as: 

```
1-59/2 * * * * /usr/local/sbin/csync2 -xv 2>/var/log/csync2.log
```
- `csync2.cfg` mapping can be: 

```
# nossl * *;
group cluster_group
{

        host ip-11-22-33-444.ec2.internal ;
        host ip-11-55-66-777.ec2.internal;
....
....
```

The whole purpose of above configuration is: We are allowing csync2 to grab VM's hostname automatically.

**Comment by mbaser** [comment]
implemented
