### ISSUE TITLE
Shib session handling

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#177]
I am not exactly sure if this is covered in cluster-mgr so creating an issue. 

Moved forward with manual cluster ( redis for session configuration ) and it ended up error like below when I initiated SSO ( SP-initiated ) in SAML. From error it seems like clustered shibboleth couldn't catch session  properly. 

When above situation appear, user do not get oxAuth login page for authentication. 

```
2018-05-10 14:07:17,578 - ERROR [org.springframework.webflow.execution.repository.NoSuchFlowExecutionException:76] - 
org.springframework.webflow.execution.repository.NoSuchFlowExecutionException: No flow execution could be found with key 'e1s1' -- perhaps this executing flow has ended or expired? This could happen if your users are relying on browser history (typically via the back button) that references ended flows.
	at org.springframework.webflow.execution.repository.support.AbstractFlowExecutionRepository.getConversation(AbstractFlowExecutionRepository.java:172)
Caused by: org.springframework.webflow.conversation.NoSuchConversationException: No conversation could be found with id '1' -- perhaps this conversation has ended? 
	at org.springframework.webflow.conversation.impl.ConversationContainer.getConversation(ConversationContainer.java:126)
```

To resolve this issue: 

 - Had to configure nginx from source with 'sticky session' module enabled. Doc: https://github.com/GluuFederation/support-docs/blob/master/howto/Manual_clustering/nginx_from_source.md

 - Redis configuration in all nodes: 
  - `protected-mode no`: so one node can connect to another node and share info.

**Comment by mbaser** [comment]
sessions are stored if one of the clustered gluu is shut down. The important thing is to use URI for metadata instead of file.
![screenshot from 2018-05-13 19 55 03](https://user-images.githubusercontent.com/6398752/39969637-6bb34230-56e7-11e8-9365-62aa5506bc4b.png)

**Comment by mbaser** [comment]
On the other hand, if you add trust relationship on node-1, idp service should be restarted  on other nodes (node-2, node-3 ...)

**Comment by mbaser** [comment]
I re-tested and not had such issue.

**Comment by mbaser** [comment]
This is duplication of #266 closing.
