### ISSUE TITLE
Ability to Define Location of TCP Proxy

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#181]
Users should be given the ability to define a TCP load-balancer location. This will satisfy requirements where F5 or Amazon ELB are utilized in lieu of twemproxy for TCP cache availability and routing. 

By default, `Cache Management` utilizes the NGINX proxy server as the TCP proxy location to install Twemproxy. In some use-cases neither of these services are necessary as the aforementioned load-balancers can serve the same purpose.

As such, users need to be able to define their proxy servers in `Cache Management`, so that cluster manager can make the adjustments to the Gluu Servers `oxCacheConfiguration`. Choosing locations and ports should also be added for the tcp load-balancer as well as redis. Related: https://github.com/GluuFederation/cluster-mgr/issues/121

**Comment by afroDC** [comment]
Potential complications may arise with automating stunnel configuration and using a load-balancer, as it will terminate the SSL connection. Further research is required on how to deal with these scenarios.

**Comment by afroDC** [comment]
![http_tcp_lb](https://user-images.githubusercontent.com/30447907/40497613-4b359374-5f42-11e8-94bc-6b18ea553e34.png)

Here's an example where the HTTP proxy and the TCP proxy are different locations. Allowing this kind of flexibility, where a user can select a different TCP proxy for caching, should be present in the `Cache Management` portion of Cluster Manager. The HTTP Proxy, which is the hostname in the certs of the Gluu Servers, will still be defined in the `Settings` portion of Cluster Manager.

**Comment by mbaser** [comment]
closed with commit 2e42c4a8dd076d0be92e30f5f8213f47fb116ecf
