### ISSUE TITLE
Migrate all old python-ldap code to ldap3

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#19]
The app presently has some old `python-ldap` dependent code. Due to this, the dependencies of the app list both `python-ldap` and `ldap3`. The old `python-ldap` dependent code should be migrated to `ldap3` and the dependency `python-ldap` removed.

**Comment by mbaser** [comment]
Ok,  I will migrate to ldap3 today.

**Comment by tecoholic** [comment]
I think I know the old code better. I will do the migration.

**Comment by mbaser** [comment]
Thanks
