### ISSUE TITLE
cluster-mgr is trying to restart 'gluu-server-3.1.2' in 3.1.3 environment

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#190]
I am trying to use the 'Use Standalone feature as primary server' ( aka. using existing Gluu Server 3.1.3 as primary ); seems like in Step-2 ( 'Changing Hostname' ); it's trying to restart 3.1.2 when I am using 3.1.3. 
Screenshots attached below: 

- First screenshot: 

![changing_hostname_1](https://user-images.githubusercontent.com/7156097/40502204-dea2dbbe-5f4f-11e8-89e0-ac86dbead29c.png)

- Second screenshot: 

![changing_hostname_2](https://user-images.githubusercontent.com/7156097/40502208-e4127c8a-5f4f-11e8-8cf5-5975a853fbb1.png)

**Comment by afroDC** [comment]
https://github.com/GluuFederation/cluster-mgr/blob/48de05b1120f63b0d32bf8d1319448bbd42d942b/clustermgr/tasks/wizard.py
