### ISSUE TITLE
Improve Start/Stop Functionality of Redis on CentOS

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#191]
Currently starting and stopping Redis on CentOS is not as convenient as cluster installations in Ubuntu. Fixing this will improve capabilities of managing Gluu Server instances.

**Comment by mzico** [comment]
@mbaser : I will install a CM 4.0 in all CentOS7 system, will see how that goes.

**Comment by mbaser** [comment]
I am not clear what Chris mentioned here

**Comment by mbaser** [comment]
Redis Server is only installed on cache server and we have no issues for starting and stopping. Closing this issue until someone reports.
