### ISSUE TITLE
Server That Previously Had Replication Configured Showing Configured When Not

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#192]
![image](https://user-images.githubusercontent.com/30447907/40516284-aef12d50-5f75-11e8-995d-9bb95b126bc8.png)

I removed a dev server, re-imaged it and added it back to cluster manager. After that I installed Gluu Server and went to LDAP replication. There I found that there's some sort of flag where it assumes replication is configured although it's not (see image). This shouldn't show configured or show the `Re-Enable Replication` and `Disable Replication` buttons or `Re-Deploy All` buttons.

**Comment by mbaser** [comment]
I just tested, it does not show `Re-Enable Replication` and `Disable Replication` buttons, if you press "Remove" on the dashboard. A server can only be removed from cluster by hitting "Remove" button on the dashboard. Cluster-mgr and opendj won't be aware Physically shutting down or re-imaging a server.
