### ISSUE TITLE
Non-fatal "LDAP:error code 49" On New Servers After Primary Change

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#193]
When replicating a new server after changing the primary server, the following error is showing in Cluster Manager:

```
The following errors were encountered reading the configuration of the existing servers: Error on c6.gluu.org:4444: An error occurred connecting to the server. Details: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials] The replication tool will to try to update the configuration of all the servers in a best-effort mode. However it cannot guarantee that the servers that are generating errors will be updated.
```

In this particular scenario, I believe it may be due to the fact that because I changed the primary server from c6.gluu.org to c7.gluu.org and tried to enable replication with c7.gluu.org as host1, it presumed some type of issue. The error is non-fatal and replication gets enabled.

Thoughts @mbaser ? It doesn't seem to happen all the time.

**Comment by mbaser** [comment]
I changed primary server and tried to disable replication on a node, i get this arror
![screenshot from 2018-05-29 08 39 44](https://user-images.githubusercontent.com/6398752/40631043-c8fc5a86-631b-11e8-891f-62c0a2b45dc8.png)

It seems, changing primary server is not a good idea.

**Comment by mbaser** [comment]
With WrenDS, this is not an issue anymore. So closing.
