### ISSUE TITLE
Server That was Previously Part Of Cluster Cache Assumed Installed

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#194]
![image](https://user-images.githubusercontent.com/30447907/40517029-f1d1f750-5f78-11e8-8d04-04c78212394e.png)
Another issue of another server having some sort of flag in the db vs actually being checked to have the correct services. In this case c6.gluu.org doesn't have Redis or Stunnel installed but because it was part of the cluster before, it's assumed to be active.

Perhaps removing all information pertaining to a server when it's removed from the cluster will fix this and https://github.com/GluuFederation/cluster-mgr/issues/192

**Comment by mbaser** [comment]
It is confusing, i was annoyed with this before

**Comment by afroDC** [comment]
Can we remove all information about a server from the Cluster Manager database?

**Comment by mbaser** [comment]
closed with commit edd544ed3ae98681e3678d22ae6c7674fb82ad4f
