### ISSUE TITLE
Intermitten Issues with Redis Connection

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#195]
While testing server redundancy in a default Cluster Manager configuration there will be intermittent issues where Jedis will timeout while trying to connect to Redis. These are one off instances and functionality is restored upon another request, but it's worth looking in to and researching the root cause.

Something like this can be found in the oxAuth.log:

```
2018-05-24 23:28:47,946 ERROR [qtp1744347043-13] [org.xdi.oxauth.exception.UncaughtException] (UncaughtException.java:41) - Jersey error.
redis.clients.jedis.exceptions.JedisDataException: ERR Connection timed out
```

This can sometimes happen with oxTrust/Identity as well. I need to determine whether the issue is with Jedis->Redis or if it's an issue with stunnel or Twemproxy. Further research is required.

If it's a Jedis issue, we'll have to look further into our implementation with oxauth.

**Comment by mbaser** [comment]
We get rid of twemproxy. I did not see this on recent installations. Closing up to one faces again.
