### ISSUE TITLE
Log viewer / Review logs

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#196]
Sometime I use to get orange banner like below. ".... Kindly review the log of EACH SERVER before restarting the process". 

IMHO, this message is kind of not-clear. If Cluster-mgr can tell me "which server" or "which log" or "which service log" should I check; that will really helpful. 

![reviewlogs](https://user-images.githubusercontent.com/7156097/40620507-ae188220-625e-11e8-86ea-a3132982e9b4.png)

**Comment by afroDC** [comment]
@mzico the logs are in the browser. You have to click on the blue bar with the hostnames and it will drop down the activity log. Any error is in a different color with a red x on the right, similar to the green check in your screen shot.

Perhaps we can extract errors and present them without having to go through the activity logs.

**Comment by mbaser** [comment]
Implemented by commit https://github.com/GluuFederation/cluster-mgr/commit/31d4d4c7003b0cc9221cccc730245d9fededa08c

![Screenshot_2020-02-11_17-09-57](https://user-images.githubusercontent.com/6398752/74244146-0a7d4580-4cf2-11ea-9289-103dac242a17.png)
