### ISSUE TITLE
Cannot Continue Install While Using Cloud Based Loadbalancer

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#199]
While trying to use a Digital Ocean load-balancer instead of the default proxy server that is generally installed with Cluster Manager, I am unable to continue the process of installing Gluu Servers. Inability to access the proxy/load-balancer through SSH should not be limiting. 

![image](https://user-images.githubusercontent.com/30447907/40683848-565825ac-6355-11e8-8e71-1890eb5cc039.png)

**Comment by mbaser** [comment]
closed with commit 2e42c4a8dd076d0be92e30f5f8213f47fb116ecf
