### ISSUE TITLE
Central Log Management

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/cluster-mgr#2]
It would be nice if you could also manage logs from this console. For example, configure ActiveMQ, Postgress, and messageConsumer.

https://github.com/GluuFederation/replication-mgr/blob/master/mockup/Gluu%20Logs.png

ActiveMQ has statistics http://activemq.apache.org/statisticsplugin.html

**Comment by iromli** [comment]
Basic support for reading oxAuth logs are done. Feel free to reopen if something's missing or create new one.
