### ISSUE TITLE
Cluster-mgr freezes after deploying servers

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#21]
You can no longer click any of the buttons in the menu after you deploy a server. A workaround is to navigate back to the main page. I'm not sure why it stops.

**Comment by mbaser** [comment]
I never faced this issue. I am using Firefox and Chrome. May be due to browser.
 

Sent: Tuesday, September 26, 2017 at 9:01 PM

**Comment by afroDC** [comment]
Issue hasn't continued. Closing
