### ISSUE TITLE
No Keygen.jar In ".clustermgr/javalibs/" Directory

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#211]
`Keygen.jar` is missing from Cluster Manager for cluster manager.

https://github.com/GluuFederation/cluster-mgr/blob/master/clustermgr/tasks/keyrotation.py#L34

```
[2018-07-17 15:56:36,931: WARNING/ForkPoolWorker-1] clustermgr.tasks.keyrotation.schedule_key_rotation[2ef93277-f395-42f5-a9a7-9b17844a74e9]: Unable to generate keys; reason=Error: Unable to access jarfile /root/.clustermgr/javalibs/keygen.jar
```

**Comment by iromli** [comment]
@afroDC are you using container or manual installation?

**Comment by iromli** [comment]
oh nevermind, I think i know the issue with missing this JAR file

**Comment by iromli** [comment]
The `gluufederation/clustermgr:latest` docker image has been modified to include `keygen.jar`

**Comment by afroDC** [comment]
It's also missing from the CE editions of Cluster Manager. Can you have a look at that @iromli ?

**Comment by iromli** [comment]
@afroDC You mean missing in the docs?
