### ISSUE TITLE
[GUI enhancement] Description of Hostname and IP Address

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#218]
Last two options are for Gluu Server which we are going to use as primary server for our cluster setup. 

Suggested syntax: 

- 'Current Hostname of primary Gluu Server' instead of current 'Current Hostname' 
- 'Current IP Address of primary Gluu Server' instead of current 'Current IP Address' 

![clarification](https://user-images.githubusercontent.com/7156097/43850595-fed7e8ea-9afd-11e8-8bcf-ca76e718d9ae.png)

**Comment by afroDC** [comment]
`New Hostname` should also read as `Load Balancer Hostname` to avoid confusion. Also `Load Balancer IP Address` should be optional and not a requirement as some of the cloud providers don't have static IP address for their load balancer.
