### ISSUE TITLE
Cannot Remove Server Recently Added

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#219]
I added a server to my dashboard without installing Gluu or running any task on it. Trying to remove in it results in the following:

![screenshot from 2018-08-20 13-29-51](https://user-images.githubusercontent.com/30447907/44359390-5e042f80-a47d-11e8-8d2e-089b40ceff29.png)

This server doesn't remove itself from the dashboard either. Perhaps we should run a check to see if Gluu Server is even installed first, and if not, remove the server from the db/Dashboard.

**Comment by afroDC** [comment]
Same issue with a server that doesn't have anything configured but Gluu Server installed


![screenshot from 2018-08-20 13-52-43](https://user-images.githubusercontent.com/30447907/44360412-67db6200-a480-11e8-85db-04f785c961a8.png)

**Comment by mbaser** [comment]
closed by commit faedfc3c83bd544cf778c0b5e2087ef9011d9bd3
