### ISSUE TITLE
Automate configuring /etc/gluu/conf/ox-ldap.properties to include all servers in the cluster topology for 3.0.*.

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#22]
In 3.0.*, oxAuth stores cache tokens in LDAP. The /etc/gluu/conf/ox-ldap.properties file must include all the servers in the cluster so that they can locally store the cache.

**Comment by mbaser** [comment]
Implemented within commit db4ccbc843db4ababeff0b21b391be5c00e67a22
