### ISSUE TITLE
Remove Testing Repos On 3.1.4 Release

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#220]
https://github.com/GluuFederation/cluster-mgr/blob/master/clustermgr/tasks/cluster.py#L908

https://github.com/GluuFederation/cluster-mgr/blob/master/clustermgr/tasks/cluster.py#L902

https://github.com/GluuFederation/cluster-mgr/blob/master/clustermgr/tasks/cluster.py#L863

Once we are close to release, removing the testing repos will be necessary.

**Comment by mbaser** [comment]
done
