### ISSUE TITLE
FS replication uninstall not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#226]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7156097/45266709-daf34b00-b424-11e8-9f28-a987d83e70d3.gif)

**Comment by mzico** [comment]
Screencast: https://youtu.be/2PtSETEzTDs

**Comment by mbaser** [comment]
I have no issue with uninstalling csync2

**Comment by mbaser** [comment]
I checked on 3.1.4 and 3.1.3.1, it is working. Closing until we replicate.
