### ISSUE TITLE
Server removal dependent on nginx LB ( even if external LB is being used )

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#227]
We need a better way to handle Server ( node ) removal from cluster. Right now this operation is completely dependent on nginx load balancer ( to configure nginx.conf I believe ). But if user doesn't use nginx at all and use external LB instead of nginx; removal of server will fail.

**Comment by mbaser** [comment]
If you are using external load balancer, clustermgr won't try to remove from nginx.conf, I tested and did not faced this issue.
