### ISSUE TITLE
Find out Secure communication between oxAuth and Redis Cache

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#23]
Redis communication is insecure, so we must wrap redis to use stunnel, on both ends, to protect the communications with SSL/TLS.

**Comment by tecoholic** [comment]
By both ends, if you mean from oxAuth ----> Redis and Redis -----> oxAuth, stunnel will not be of help. Unless oxAuth communicates over SSL the transport would be insecure. Kindly refer to the below diagrams for clarity.
![without stunnel](https://user-images.githubusercontent.com/383862/30897289-0e019fce-a373-11e7-99ca-0e0cdbee4664.png)

![with stunnel](https://user-images.githubusercontent.com/383862/30897291-132c4e40-a373-11e7-811e-a707e2bc27c9.png)

Until we get SSL encrypted data from oxAuth, the communication channel would be insecure.

**Comment by afroDC** [comment]
Will the data coming from oxAuth to stunnel be on the same server? If that's the case, that should be fine as the server is protected from external events.

**Comment by tecoholic** [comment]
I think I now understand your "both ends" situation.
![oxauth and redis on different hosts](https://user-images.githubusercontent.com/383862/30923350-426308ba-a3c9-11e7-9acc-1f1b314b9bf6.png)

This could be done versions upto 3.1.1. Agreed.

**Comment by afroDC** [comment]
Yes, exactly. That would be secure communication.
