### ISSUE TITLE
Logging Management Should Collect Passport and Shibboleth Logs

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#233]
The Passport logs are located at `/opt/gluu/node/passport/server/logs/` and are incremented by day. For example:

```
passport-2018-10-06.log  passport-2018-10-08.log  passport-2018-10-17.log
```

The start.log may also have useful information.

The shibboleth logs are located at `/opt/shibboleth-idp/logs/`:

```
idp-audit.log  idp-consent-audit.log  idp-process.log  idp-warn.log
```

`idp-process.log` is generally the most useful regarding current status information.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/gluu-passport/issues/48 working on getting that done for later version @iromli

**Comment by mbaser** [comment]
Impelemnted by https://github.com/GluuFederation/cluster-mgr/commit/64566c2827d6d89ebd45f6f619d936c44489a686
