### ISSUE TITLE
In CentOS and Redhat Chroot Login Failure Should Be Caught

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#237]
If Cluster Manager cannot ssh into the chroot, an error should be shown. Something similar to this is command is run by Cluster Manager:

```
ssh  -o IdentityFile=/etc/gluu/keys/gluu-console -o Port=60022 -o StrictHostKeyChecking=no -o PubkeyAuthentication=yes root@localhost
```

If the pub key `IdentityFile` is wrong it will throw an error. Also if the sshd inside the chroot isn't running correctly, the login will fail like so:

```
ssh: connect to host localhost port 60022: Connection refused
```

We could either catch these particular errors, or find out what a successful response looks like and throw whatever error does not match to the user in the case of a failure.

**Comment by mbaser** [comment]
commit e8cf627 to 3.1.4-refactor closes this issue
