### ISSUE TITLE
Add Option To Have Cluster Manager SSH as sudoer

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#242]
In Settings, there should be an option to provide a username which Cluster Manager will log in with and then login as sudo. For example `ssh dc@example.com` and then `sudo su -` to become root.

I'm not sure paramiko would allow this type of connection, but if possible, this would mitigate some security requirements.

**Comment by mbaser** [comment]
Our main issue is uploading/downloading files.
We can’t simply upload files if we make ssh connection with non-root user
Some files can’t be read by ordinary users, so we must `sudo cat <file>` and read stdout
So this work won’t be a single line of change, instead we should carefully scan line by line
For uploading files, we should upload to `/tmp `and run `sudo cp /tmp/<file> <destination>`

**Comment by mbaser** [comment]
It seems it is not possible to implement this. Closing.
