### ISSUE TITLE
Monitoring setup failing in CentOS7.5 - aws

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#244]
Screenshot attached: 

![monitoringcentos7_aws_1](https://user-images.githubusercontent.com/7156097/49034169-c3e80d80-f176-11e8-9b85-316afa183343.png)
![monitoring_centos7_2](https://user-images.githubusercontent.com/7156097/49034172-c77b9480-f176-11e8-93f4-d36240d57377.png)
![monitoring_centos7_3](https://user-images.githubusercontent.com/7156097/49034176-c8acc180-f176-11e8-9e99-c0692f6ea5cf.png)

**Comment by mbaser** [comment]
@mzico how can I resolve this issue?

**Comment by mzico** [comment]
@iromli @mbaser : Yes, I think same. With third or forth attempt it looks good to me. AWS networking issue...
