### ISSUE TITLE
If Server ID 1 Goes Down, Functionality Goes Away

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#246]
The server listed in Server ID 1 seems to be the basis for most functionality, even if it's not set as the Primary server. LDAP Replication Status fails and functionality is degraded. Certain features elsewhere are also degraded. We should detach from reliance on the first server in the list.

**Comment by afroDC** [comment]
To recreate this issue, you can either hard shut down Server ID 1 or restart it and try to use Cluster Manager

**Comment by mbaser** [comment]
Do you have a suggestion?

**Comment by nynymike** [comment]
The requirement is fairly open ended. The customer should be able to take this data, and restore the system from it. It might be helpful to have an option to specify whether you should do an ldif data backup, or a db backup. Another consideration is how to make this backup happen while the system is running.

The problem with VM backups is that they may not work, if the system was in an unstable state at the time of the backup. This backup process in a way is similar to upgrade, in that the output can be used to initialize a new system.

**Comment by afroDC** [comment]
> Do you have a suggestion?

We just need to make sure that Cluster Manager will iterate through the rest of the servers and provide functionality. Right now it seems to stop at Server ID 1(0) on the list and upon connection failure, will stop functioning.

**Comment by mbaser** [comment]
WrenDS allows us to change primary server, so if primary server dies, you can make one of the nodes as primary.
![Screenshot_2019-12-24_19-49-52](https://user-images.githubusercontent.com/6398752/71420511-b1e0e300-2686-11ea-9008-40c16623acaa.png)

Thus, this issue is resolved.
