### ISSUE TITLE
Length of state field

### ISSUE THREAD

**Issue by bfar** [GluuFederation/cluster-mgr#250]
https://github.com/GluuFederation/cluster-mgr/blob/a06af6c829234d7cf402338d514a7a5e8204d60c/clustermgr/forms.py#L174

Some countries have states with 3 letter abbreviations 
Some countries have no states.

min length should be zero, max length should be 3?

**Comment by afroDC** [comment]
That makes sense. I don't think the state even has to be the 2 or 3 letter format like the country and can be the full state name.

Can you remove this requirement @mbaser ?
