### ISSUE TITLE
Cache configuration in RHEL, cluster-mgr trying to load deb package in RPM

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#253]
In RHEL7 Gluu Server system, cluster-mgr is trying download deb package instead of rpm. 
Screenshot shared with Mustafa.

**Comment by mbaser** [comment]
CM is doing well. That installation was for proxy and his proxy was ubuntu

**Comment by mzico** [comment]
Yes, seems like it was RHEL issue. 
CM couldn't install Redis due to library issue, here is the workaround: 

 - installed this in both Gluu Server RHEL 7 host ( not container ): https://rpmfind.net/linux/epel/7/x86_64/Packages/j/jemalloc-3.6.0-1.el7.x86_64.rpm
 - run `yum history sync` 
 - Re-Run 'Cache Configuration'
