### ISSUE TITLE
Linux packages for Cluster Manager

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/cluster-mgr#254]
Customers need a way to install CM on a VM without Internet. We should publish a Linux package for Ubuntu 16 and 18.

**Comment by mbaser** [comment]
many commits were done for offline installation. still needs some work.

**Comment by mbaser** [comment]
I am not sure we can do this. CM is very dynamic and we are committing/fixing many times each day.
Instead of linux packages, I prepared a static build doc: https://github.com/GluuFederation/cluster-mgr/blob/4.0/static_build.md

In my opinion we can close this issue.

**Comment by mbaser** [comment]
Closing, since we have static build guide.
