### ISSUE TITLE
Implement Casa clustering into CM

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/cluster-mgr#258]
Since Casa lives in the same server where Gluu runs I guess we can leverage the same strategies in CM so Casa can be clustered too.

Since LDAP servers are already synced, we would only need to keep synced the following:
- Directories `/opt/gluu/jetty/casa/plugins` and `/opt/gluu/jetty/casa/static` (requires deep/recursive sync)
- File `/opt/gluu/jetty/casa/casa-cors-domains`  (if it exists)

**Comment by mbaser** [comment]
we are not providing an option for installing Casa in CM. I don't know how to implement these.

**Comment by mbaser** [comment]
@jgomer2001 is this still relevant with 4.1?

**Comment by mbaser** [comment]
This issue is totally related to casa clustering. To have casa cluster we need oxd clsuter first. So casa cluster will be implemented after oxd clsutering.

**Comment by mbaser** [comment]
Implemented
