### ISSUE TITLE
Upgrade 'cluster-mgr' throwing error afterward

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#259]
Went to 'upgrade' cluster-mgr from Cluster-Manager GUI. 
Now dashboard is throwing error: 

![Upgrade_cluster_mgr](https://user-images.githubusercontent.com/7156097/56098011-3d339300-5ec1-11e9-8152-b696a3297f8f.PNG)

**Comment by mbaser** [comment]
Replacing branch master with 3.1.6 resolved this issue
