### ISSUE TITLE
Build ngingx packages with sticky session

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/cluster-mgr#266]
We need nginx with stikcy session module included as described in issue #177 (https://github.com/GluuFederation/cluster-mgr/issues/177) Compiling a package on production server is not a good idea, since it requires many packages to be installed. We need to build deb/rpm packages, currently for centos7, rhel7 and ubuntu16.

**Comment by nikdavnik** [comment]
I think here we need bash script that will deploy nginx from souce with stick session enabled. 
nginx deb package ifself depends on many other debs, nginx-core, nginx-common, nginx-full etc, so we can not provide all this list of packages, also gluu is providing only gluu deb packages and not packages for other softwares. Here we can just make bash script that will help others to deploy nginx with sticky session
Is bash script acceptable option here @mbaser ?

**Comment by mbaser** [comment]
@nikdavnik No
Admins won't want to compile software on load balancer. Lots of library and compiler components should be installed on load balancer VM that is not acceptable, and doing this through cluster manager is not logical.

**Comment by mbaser** [comment]
Implemented in https://github.com/GluuFederation/cluster-mgr/commit/2e11891a5ceb5665bdf83f682be8146d43a661fa
