### ISSUE TITLE
CM Monitoring installation in CentOS7 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#271]
We are getting below error messages at the time of monitoring tool installation. However, it doesn't affect feature to work properly. 
![Monitoring_fake_error](https://user-images.githubusercontent.com/7156097/64201779-16b4cb00-ce55-11e9-9678-e11fde5f81b4.PNG)
![monitoring_fake_error_2](https://user-images.githubusercontent.com/7156097/64201781-16b4cb00-ce55-11e9-8ce0-91977c0a9e44.PNG)
![monitoring_fake_error_3](https://user-images.githubusercontent.com/7156097/64201782-174d6180-ce55-11e9-9491-abe495eebd28.PNG)
![Monitoring_fake_error_4](https://user-images.githubusercontent.com/7156097/64201783-174d6180-ce55-11e9-955a-0cc3be7045f0.PNG)

**Comment by mbaser** [comment]
In 4.0 with new installer, this issue was resolved.

![Screenshot_2019-12-24_21-21-04](https://user-images.githubusercontent.com/6398752/71424511-45c0a800-26a3-11ea-970a-898ad1db2022.png)

Hence closing the issue.
