### ISSUE TITLE
Implement Redis Cluster

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/cluster-mgr#273]
Currently, CM uses single redis server. We need to implement redis cluster.

**Comment by mbaser** [comment]
Currenlty Sentinel cluster is not supported by gluu, we need to wait this issue to be implemented: https://github.com/GluuFederation/oxCore/issues/144

**Comment by yuriyz** [comment]
@mbaser sentinel connection type support is added, you can resume work on this ticket.

**Comment by mbaser** [comment]
Implemented by commit 5c02a359fe64dbd6f6e0b4d23a16d38adb0293fd
