### ISSUE TITLE
Cluster Manger should remove gluu node on removal

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/cluster-mgr#274]
Trying to remove a Gluu node from cluster manager 4.0 beta

1- Logged in to CM4 as admin user
2- Added 2 gluu server node
3- Tried to remove the non primary node with option "Disable LDAP replication"
4- Got success message regarding removal but node is still there

![image](https://user-images.githubusercontent.com/20181082/67960019-ab526400-fc1f-11e9-89d9-2649c44642d8.png)

**Comment by mbaser** [comment]
closed by commit 5711034e62d9a1b7fad7b830d7f93053f0a66e7d
