### ISSUE TITLE
Add License Agreement note in UI

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/cluster-mgr#279]
Related to issue [278](https://github.com/GluuFederation/cluster-mgr/issues/278), we should add a note in the UI that tells they are required to accept the license agreement to use the software.

**Comment by mbaser** [comment]
There is
![Screenshot_2020-01-15_21-35-26](https://user-images.githubusercontent.com/6398752/72461014-18b57000-37df-11ea-9643-102dce94f092.png)
