### ISSUE TITLE
"Dry Run" improvement 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#284]
In vanilla VM, "Dry Run" looks like below: 
![Capture](https://user-images.githubusercontent.com/7156097/72667916-97302e80-39e6-11ea-92b9-530f9b83ac9d.PNG)

I think there is place of some improvements here, something like: 

 - When there is no software installed / aka. no port open. If possible... put banner like "16379 / Port unreachable / may be no software installed for this port?" 
- Or, we can put this in doc that.. if someone get this output like above.. it means.. no software is installed. 

Suggestion? @mbaser @shmorri

**Comment by mbaser** [comment]
Dry run check port accessibility between servers. If they are empty: (a) CM can't open server port, (b) firewall denies access.

**Comment by mzico** [comment]
@mbaser : Correct. We should improve that UI. Operation is perfectly fine but we should 'deliver something more clear' to user.

**Comment by mbaser** [comment]
Dry run on fresh Ubuntu 16, all good
![Screenshot_2020-01-20_11-45-59](https://user-images.githubusercontent.com/6398752/72711674-844e6300-3b7a-11ea-9df3-b3e6b558c844.png)

**Comment by mbaser** [comment]
> @mbaser : Correct. We should improve that UI. Operation is perfectly fine but we should 'deliver something more clear' to user.

Please explain how to improve.

**Comment by mzico** [comment]
@mbaser : you need more explanation after chat? Please let me know..

**Comment by mbaser** [comment]
closed by commit https://github.com/GluuFederation/cluster-mgr/commit/967ebbd687542f0bf896f12299c5cadad20edf7a
