### ISSUE TITLE
Gluu Server uninstallation is buggy

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#285]
Uninstalling Gluu Server from Cluster Manager is buggy. I'll add points and situations I am facing when  I am going to uninstall Gluu Server from CM control page.

**Comment by mbaser** [comment]
I just tested on ubuntu 16, I did not face any issue when I remove gluu server from cluster
![Screenshot_2020-01-20_11-24-36](https://user-images.githubusercontent.com/6398752/72710233-adb9bf80-3b77-11ea-96a7-c68582dc7e88.png)

**Comment by mzico** [comment]
@mbaser : I will share a video. I had single server ( Gluu Server ) installed in all Ubuntu 18 machines.

**Comment by mzico** [comment]
here is the video link: https://youtu.be/w2brVHg1i7M


thing is:
- ‘removing Gluu’ server throwing error.
- though above one threw error but with page refresh… I don’t see that server in CM management page.
- I had to manually remove Gluu Server from VM

now..
we know… we have to ‘manually’ remove Gluu Server
but.. I believe there might be some improvements in number 1 and 2

What do you think @shmorri @mbaser ?

**Comment by mbaser** [comment]
Implemented in commit 91253b9
