### ISSUE TITLE
SAML and Passport absent in oxTrust

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#286]
Installed Gluu Cluster Manager 4.0-5 and installed oxAuth, oxTrust, Shibboleth and Passport. 
Though they are installed 'inside' but in GUI they are absent. Screenshot below. 
![Capture](https://user-images.githubusercontent.com/7156097/72686356-6967ea00-3ab9-11ea-9c2d-7f8782248b78.PNG)

**Comment by mbaser** [comment]
It seems setup.py issue

**Comment by mbaser** [comment]
New issue is created on setup.py https://github.com/GluuFederation/community-edition-setup/issues/630

**Comment by mbaser** [comment]
Implemented in setup.py https://github.com/GluuFederation/community-edition-setup/commit/e36f9982ba9c59aee1e1c7117756485c2e59a29a
