### ISSUE TITLE
Cluster should run clean up python script which should iterate via buckets and remove expired data

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/cluster-mgr#293]
In cluster environment we should switch off oxauth built-in cleaner (by setting `cleanServiceInterval` to `-1`).
Cluster should run clean up python script which should iterate via buckets and execute:

```
DELETE FROM `<bucket_name_here>` WHERE ( del = TRUE AND ( oxAuthExpiration <= "2020-03-25T13:12:25.975" OR exp <= "2020-03-25T13:12:25.975" ) ) LIMIT 10000
```

Also this query can be slow, Fujio suggested to create index which is ordered by date which we use in filtering then it will work much faster. exp DESC` (or maybe `exp ASC` ?).

**Comment by mbaser** [comment]
@yuriyz Clustermgr does not support couchbase

**Comment by yuriyz** [comment]
@mbaser we don't need it for couchbase anymore because we added TTL support. However we need it for LDAP to re-use in CM and in `cleaner-pod`.

**Comment by mbaser** [comment]
Implemented in https://github.com/GluuFederation/cluster-mgr/commit/91a8d291936b862bf6e9778bc81492bc3e4b1f26
