### ISSUE TITLE
Issue when using oxTrust password different from ldap admin password

### ISSUE THREAD

**Issue by alexandre-zia-ifood** [GluuFederation/cluster-mgr#297]
If during setup of primary node,  oxTrust Password is set different from ldap admin password, 
On installing a second non primary cluster node, 

clustermgr/tasks/server.py on line 655 will get setup.properties.last.enc from primary node and try to decrypt it using ldap admin password, however it is encrypted with oxTrust password

`
cmd_unenc = 'openssl enc -d -aes-256-cbc -in /install/community-edition-setup/setup.properties.last.enc -k {}'.format(server.ldap_password)
`

So not possible to install secondary nodes

**Comment by nynymike** [comment]
You need to open this on https://support.gluu.org  You are probably not following the instructions properly.
