### ISSUE TITLE
ClusterMgr4 / 4.1-7 / breaking java keystore in standalone Gluu Server

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#303]
Using 'Click Here to Use Your Standalone Gluu Server' to build a cluster. 
I had one working Gluu Server 4.1 which I used as 'seed' to prepare my Gluu CE cluster. 
After adding first server, CM is messing java keystore ( cacerts ), which resulting oxTrust error. 

Workaround is: 

 - Continue installing 2nd Node
 - Get 'cacerts' from 2nd node and put it inside 1st Node ( that means, match both node's java keystore ). 
 - Restart all services in 1st Node.

**Comment by mbaser** [comment]
CM, by default does what you explained

**Comment by mbaser** [comment]
Here is the process you were describing
![Screenshot_2020-06-26_13-30-08](https://user-images.githubusercontent.com/6398752/85848678-3a654b00-b7b2-11ea-9033-44484a997fa0.png)
