### ISSUE TITLE
ClusterMgr4 / 4.1-7 / wrong sequence for nginx installation

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#304]
Using "Standalone" procedure to build my cluster. 
Just after adding "Standalone" system, "Go to install Nginx Proxy Server" appearing in bottom. 

![shouldnt_do_nginx](https://user-images.githubusercontent.com/7156097/81111277-69fa8400-8ee2-11ea-9c26-c86a2be84db4.PNG)

User go to install nginx server, it's completed. 
But.... there is just one server yet in this cluster. That means, nginx has entry for one server like below, which is wrong. Nginx configuration should have information for ALL nodes.. not just single one. 

```
http {
  server_tokens off;
  upstream backend_id {
  sticky;
  server ip-172-31-3-146.us-west-2.compute.internal:443 max_fails=2 fail_timeout=10s;
  }
  upstream backend {
  sticky;
  server ip-172-31-3-146.us-west-2.compute.internal:443 max_fails=2 fail_timeout=10s;
  }
  server {
    listen       80;
    server_name  cmtest.gluu.org;
    return       301 https://cmtest.gluu.org$request_uri;
```

Nginx installation step should 'always' _after_ installing more than one nodes.

**Comment by mbaser** [comment]
Now, the button redirects you "Add Gluu server" after finishing make of gluu server as primary
