### ISSUE TITLE
ClusterMgr4 / 4.1-7 / Replication configuration should always wait for multiple Gluu Server nodes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#305]
Trying to build my CE cluster with "Standalone" system. 
"LDAP Replication" stage appearing even after installing First Node + nginx. 

Any kind of "replication" should never run for single Gluu server node. 
Both LDAP Replication and File system replication should wait for multiple Gluu Server nodes. 

![mmr](https://user-images.githubusercontent.com/7156097/81111840-526fcb00-8ee3-11ea-950f-6ea2ab1b85a8.PNG)

**Comment by mbaser** [comment]
![Screenshot_2020-05-07_17-15-03](https://user-images.githubusercontent.com/6398752/81305037-86cfbc80-9086-11ea-8bd1-338f7565e9a7.png)
