### ISSUE TITLE
ClusterMgr4 / 4.1-7 / 2nd node require all service restart after installation completion 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#306]
I couldn't make 2nd node working just after the "Gluu Server" installation completed by Cluster Manager. I had to manually restart ldap -> oxauth -> identity -> idp to make all service work in 2nd node.

**Comment by mbaser** [comment]
Implemented in commit fe004f3ef28cbe68e907b3f1efb35a45381d850e
