### ISSUE TITLE
ClusterMgr4 / 4.1-7 / OpenDJ dies after installation 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#307]
OpenDJ service can't recover from "gluu-server restart" initiated by Cluster-Manager. 
It's not happening in single CE ( when there is no Cluster Manager software ). 

OS version: CentOS7.x. 

Please talk to Ganesh if required.

**Comment by mbaser** [comment]
Implemented in commit fe004f3ef28cbe68e907b3f1efb35a45381d850e
