### ISSUE TITLE
CentOS7 / "clustermgr4-cli" command not working. 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#311]
Screenshot attached.  It's happening in Cluster-Manager 4.2: 

![Capture](https://user-images.githubusercontent.com/7156097/95022611-02399800-063e-11eb-8b7e-0130690c60e6.PNG)

**Comment by mbaser** [comment]
It is path issue,  you can start/stop:
```
/opt/clustermgr/bin/clustermgr4-cli start
/opt/clustermgr/bin/clustermgr4-cli stop
```

Document is updated accordingly. Packagers are also asked to make `/opt/clustermgr/bin/clustermgr4-cli` to `/usr/local/bin/clustermgr4-cli` so that `clustermgr4-cli` can be used without path.
