### ISSUE TITLE
Add LDAP storage for oxd

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/cluster-mgr#317]
LDAP is the best storage option for Casa in a cluster. SQL adds another task for backup. Redis is not persistent. Docs are here: https://gluu.org/docs/oxd/4.2/configuration/ldap/

**Comment by mbaser** [comment]
![Screenshot_2021-02-09_23-06-59](https://user-images.githubusercontent.com/6398752/107422126-ba66d800-6b2b-11eb-8782-30292c766e2d.png)

**Comment by mbaser** [comment]
Implemented by commit https://github.com/GluuFederation/cluster-mgr/commit/c154c70edc68cbdafc267664e10cf5af787eb967
