### ISSUE TITLE
Logs not being collected on RHEL 8

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/cluster-mgr#324]
After setting up  logs / filebeat successfully (according to the ui), the hitting **COLLECT LOGS**, logs are not showing up.

After some investigation we realized that service was not running and that if  Filebeat version is `>= 6.3`, `inputs` should be used instead of `prospects`, we use it in first line of filebeat yaml template (https://github.com/GluuFederation/cluster-mgr/blob/4.4/clustermgr/templates/filebeat/filebeat.yml#L1)

**Comment by gluuer** [comment]
We laso need to update filebeat installation procedure as described in https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html

**Comment by devrimyatar** [comment]
Fixed in commits
https://github.com/GluuFederation/cluster-mgr/commit/2357eed1740f97e7125fca089237fdf456253c0c
https://github.com/GluuFederation/cluster-mgr/commit/9e7ddc7580f0cf6718df55cdf87f8c26f7e38caa
