### ISSUE TITLE
Cluster_Setup.py

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#33]
Customize setup.py from community edition to work more in line with clustering.

**Comment by afroDC** [comment]
Researching multi-domain certificates, it looks like creating a SAN with all the servers that will be in the cluster could make certificates a non-issue.

https://geekflare.com/san-ssl-certificate/

**Comment by nynymike** [comment]
Can't you just copy the private key to all the Web servers that are configured for that dns name?

**Comment by afroDC** [comment]
This would be a solution for a more complicated high speed topology. The LDAP proxy needs a keystore that contains all the servers it connects to and I think the best solution would be a SAN, if the domains are different, or a wildcard cert if they're under the same domain. @nynymike
