### ISSUE TITLE
User should be informed if SSH isn't set up properly

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#34]
While trying to "install Gluu" the app told me it could not detect the OS verison. I failed to give cluster-manager SSH access and that's the reason it failed. We need to add the ability to notify the user more accurately why certain functions are failing.

**Comment by mbaser** [comment]
In commit cc330d4, get OS info manually while installing Gluu. So that admin is notified if SSH connection can't be established.
