### ISSUE TITLE
Allow the user to select which modules of Gluu to install

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#37]
This will alter the selections in setup.py

Install oxAuth OAuth2 Authorization Server? [Yes] :
Install oxTrust Admin UI? [Yes] :
Install LDAP Server? [Yes] :
Install Apache HTTPD Server [Yes] :
Install Shibboleth SAML IDP? [No] :
Install Asimba SAML Proxy? [No] :
Install oxAuth RP? [No] :
Install Passport? [No] :

The defaults are oxAuth, oxTrust, LDAP and Apache2(HTTPD on CentOS)

**Comment by mbaser** [comment]
closed with commit 00ce27d
