### ISSUE TITLE
Add functionality to upload LDIF file for initialising a LDAP server

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#51]
In version 1, this feature was added to address the situations where the admin can export the data from LDAP data and use it as a seed for the other servers added to the cluster. With the current version adding features like, using a primary server and auto installation of the Gluu Server.. etc., Is this feature still required?

**Comment by afroDC** [comment]
It is and if you can get it to work with the clustering process, that would be ideal.

**Comment by afroDC** [comment]
Reading over your question again, I don't think we will use ldif's as a seed, since syncrepl can copy over the data without issue. Now for larger deployments, there may need to be some sort of mechanism using ldif's, since they're roughly half the size of an indexed database.

Thoughts @tecoholic ?
