### ISSUE TITLE
Cache management fail on centos 7

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/cluster-mgr#60]
See error in the attached screen-shot
![screenshot from 2017-10-20 18 55 01](https://user-images.githubusercontent.com/6398752/31833255-aa982dc8-b5d2-11e7-9fcf-1454e91b6656.png)

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/31841467-300101fc-b5af-11e7-8df3-a63da2ff1548.png)

Cluster-mgr freezes during cache configuration installing my 3rd server. The continue option seems to be missing.

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/31841573-ab3c2f04-b5af-11e7-865c-59bcb07b223c.png)

**Comment by afroDC** [comment]
Fixed the bugs with Ubuntu. Looking into CentOS.

**Comment by afroDC** [comment]
adding 10 second wait time fixes the issue
