### ISSUE TITLE
Change install setup.py -n to setup.py

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#66]
```
    if server.os == 'CentOS 7':
        cmd = "ssh -o IdentityFile=/etc/gluu/keys/gluu-console -o Port=60022 -o LogLevel=QUIET -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=yes root@localhost 'cd /install/community-edition-setup/ && ./setup.py -n'"
        run_command(tid, c, cmd)
    else:
        cmd = 'cd /install/community-edition-setup/ && ./setup.py -n'
run_command(tid, c, cmd, '/opt/'+gluu_server+'/', no_error='debug')
```
If setup.py is run with the -n argument, it will install default regardless of user selections before install. It needs to run setup.py and force the install to continue.

**Comment by mbaser** [comment]
No, it is not a bug -n means "No interactive prompt before install starts". setup.py reads last.properties file to decide what to install. if you run setup.py without "-n" argument, it will ask you to proceed:

Proceed with these values [Y|n] 

Checking this prompt via paramiko and writin "Y" via paramiko is nonsense.

**Comment by mbaser** [comment]
Non interactivity will remain.
