### ISSUE TITLE
Daemonize redis

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#67]
In redis.conf:
```

# By default Redis does not run as a daemon. Use 'yes' if you need it.
# Note that Redis will write a pid file in /var/run/redis.pid when daemonized.
daemonize yes
```

**Comment by tecoholic** [comment]
The demonize flag is only required if we start the redis-server manually. We are managing the redis-server as a service using [init script](clustermgr/templates/redis/redis-server) which handles the redis in the background.
