### ISSUE TITLE
Installing Redis from non-standard repo

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#71]
Why are we installing redis like this:
```
self.run_command("apt-get update")
self.run_command("apt-get upgrade -y")
self.run_command("apt-get install software-properties-common -y")
self.run_command("add-apt-repository ppa:chris-lea/redis-server -y")
self.run_command("apt-get update")
```
And not just 
```
apt-get update
apt-get install redis-server
```

**Comment by tecoholic** [comment]
1. The default redis-server package in Ubuntu Trusty is in [version 2.8.4](https://packages.ubuntu.com/trusty/redis-server) and it does not support `redis-cluster`.
2. The [ppa:chris-lea/redis-server](https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server) PPA provides more upto date packages of the redis-server, currently provides version 4.4.0
