### ISSUE TITLE
Cache management hangs with no logs

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#74]
![image](https://user-images.githubusercontent.com/30447907/32117852-5e67170a-bb15-11e7-9f8c-de4f62bfe487.png)

I'm not sure if it's doing anything or not. The screen just stays like this after clicking "setup Redis"

**Comment by afroDC** [comment]
Apparently it still installs after writing some time, the logs just don't show up.

**Comment by tecoholic** [comment]
My recent test didn't show this behaviour. It logs just fine. Kindly see if you can reproduce the issue again.

**Comment by afroDC** [comment]
The install went through fine apparently. I think it failed because stunnel and redis-server were already running on those servers I installed before.
