### ISSUE TITLE
Paramiko Channels

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/cluster-mgr#76]
Implementing paramiko channels to inform user without wait to finish command.

**Comment by afroDC** [comment]
Example:

When running setup.py there's no feedback from the console, which may lead users to believe something has hung and navigate away from the page. Keeping track of setup.log as it updates will help a lot.

**Comment by ganesh-at-wiw** [comment]
+1

**Comment by tecoholic** [comment]
A new realtime logging system is in the works at the branch [tasks_using_yam](/GluuFederation/cluster-mgr/tree/tasks_using_yaml). Here is a simple demo video of it working [![Screen capture image](https://img.youtube.com/vi/e_s8_Cd5Vmk/0.jpg)](https://youtu.be/e_s8_Cd5Vmk)

**Comment by afroDC** [comment]
That looks good @tecoholic. Is there a method for showing that an error has occurred within your design?

**Comment by afroDC** [comment]
Can you also give me an idea of what framework for the backend you're using to get real-time information displayed?

**Comment by tecoholic** [comment]
A Paramiko Channel is used to get the info on realtime.  That is stored in the redis. The browser queries the server every 500ms and updates the UI.

**Comment by tecoholic** [comment]
> Is there a method for showing that an error has occurred within your design?

Yeah. If you look right of the command, you will notice icons which provide context. The background color would also be changed. It is still in the works
