### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#78]
Things seem a little slow and unresponsive, like they take too much time to process. Are there any ways we can improve speed in the framework we're currently using or will this require a revamping of the system?

**Comment by afroDC** [comment]
```
Arunmozhi P
I think the recent lag is, a couple of views are running queries on remote servers before returning the response. We should move it to JS for quick response.
```

**Comment by mbaser** [comment]
recent version of CM is responsive all the time
