### ISSUE TITLE
Copy the CA Cert of the provider to the Consumer

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#8]
Presently the Syncrepl configuration is only for `ldap` protocol. For the `ldaps` protocol, the server certificate of the providers should be available for all the consumers to established trusted connections. 

Cluster manager should copy the CA Cert mentioned in the provider's `tls_cacert` value to the consumer to a predetermined location and configure syncrepl to use it.

**Comment by iromli** [comment]
Somehow, the provider cert is not copied to consumer. Both provider and consumer are chrooted. I'm still investigating, but I will keep this issue re-opened.

**Comment by iromli** [comment]
Also, replication didn't work as expected. Likely due to missing cert.

![screenshot from 2017-05-06 06 25 03](https://cloud.githubusercontent.com/assets/231601/25767598/20d2cb06-3225-11e7-972f-731a30aa9fba.png)

**Comment by iromli** [comment]
Fixed in `master` branch
