### ISSUE TITLE
Update cluster-mgr

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#81]
Cluster manager should have an easy method to download and integrate new updates

**Comment by tecoholic** [comment]
Once we have a package, we should be just be able to do `apt-get update && apt-get install gluu-clustermgr` or `pip install gluu-clustermgr --upgrade` depending on where were are hosting our package.

**Comment by afroDC** [comment]
I'm currently working with Adrian on getting the program packaged. We will need to test this once we get that package completed.

**Comment by afroDC** [comment]
`pip install --upgrade clustermgr` has worked with minor fixes. More testing is required, as any database change will also require a `clustermgr-cli upgrade db` call as well, but there is nothing to suggest this will not work.
