### ISSUE TITLE
oxd integration/Login functionality

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#86]
We need some method to authenticate the user before they can access Cluster Manager. Preferably authenticated through oxd on port 443.

**Comment by iromli** [comment]
Login using default admin user is implemented in `auth` branch.
For oxd login, I'm waiting for patches in oxd-python.

**Comment by iromli** [comment]
User authentication using oxd is implemented in `auth` branch

**Comment by iromli** [comment]
Merged to `master` branch

**Comment by mbaser** [comment]
implemented
