### ISSUE TITLE
Security Audit Log for Cluster Manager

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#87]
Any time there is a change or modification to the cluster, there should be a log event to track who did what and when. This ties back in to the issue [#86](https://github.com/GluuFederation/cluster-mgr/issues/86)

**Comment by iromli** [comment]
We can logs authenticated user activity on visited pages.

**Comment by mbaser** [comment]
implemented by https://github.com/GluuFederation/cluster-mgr/commit/9b2224dddac6717ce29a2b5e210e1ce9d598b710
