### ISSUE TITLE
adding provider and consumer using ldaps+StartTLS protocol, doesn't replicate

### ISSUE THREAD

**Issue by jschristie** [GluuFederation/cluster-mgr#9]
While provider and consumer, if LDAPS+StartTLS is selected as connection protocol, replication doesn't happen and replication fails. Whereas if ldaps is selected, replication is successful without any issue.

**Comment by iromli** [comment]
Thanks for the report. I will take a look on it.

**Comment by nynymike** [comment]
We may just want to disable StartTLS.   LDAPS is good enough. We can push this issue off to another release if it helps.

**Comment by iromli** [comment]
> We may just want to disable StartTLS. LDAPS is good enough.

Noted.

**Comment by iromli** [comment]
LDAP + StartTLS protocol is disabled temporarily.
