### ISSUE TITLE
Improve the way in which celery tasks are started/stopped

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/cluster-mgr#90]
Version 1 had the ability to start and stop celery worker as a service. A similar solution should be implemented.

**Comment by afroDC** [comment]
As it stands, the method to stop` clustermgr-celery`, `clustermgr-beat` and `clustermgr-cli run` tasks is to use this command `ps aux | grep 'cluster' | awk '{print $2}' | xargs kill -9`

**Comment by afroDC** [comment]
https://github.com/GluuFederation/cluster-mgr/commit/2e2d2dd364c17e0aa020b6f512ceac4996dffc91
