### ISSUE TITLE
Monitor Gluu server components

### ISSUE THREAD

**Issue by mzico** [GluuFederation/cluster-mgr#93]
In pre 3.x cluster, we are monitoring Gluu server components like oxauth, identity, idp, httpd, replication tools like nutcracker, twemproxy, memcached etc. Also we are checking if 'login page' is coming or not with 'curl https://$DOMAIN/oxauth/login'. 

If there is any error in any component in whole cluster; monitoring module can pull that server out of load balancer pool and take necessary action; it also email to administrators on situation automatically. 

It will be nice if we can implement something like this here in cluster-mgr monitoring. 
Details are available internally.

**Comment by afroDC** [comment]
https://github.com/GluuFederation/cluster-mgr/issues/69

An extension of this previous ticket with more details

**Comment by afroDC** [comment]
From testing, this can be achieved by running curl commands on the server locally. For example:

oxTrust check:

```
curl -skL -o /dev/null -w '%{http_code}' http://localhost:8082/identity/restv1/scim-configuration
```

oxAuth check:

```
curl -skL -o /dev/null -w '%{http_code}' http://localhost:8082/oxauth/
```

These will return 200 if the service is active and returns a response.

**Comment by iromli** [comment]
Perhaps directly checking `http://localhost:8082/oxauth/.well-known/openid-configuration` to bypass page redirect?

**Comment by afroDC** [comment]
Going further on my previous point, a 200 does not always necessitate that the service is working as expected. We should check that there is data in a JSON Body response for oxAuth and oxTrust, an XML response for Shibboleth, and generally speaking, if passport isn't working, it will return a 502.

Health checks of endpoints:

oxauth:

```
http://localhost:8082/oxauth/.well-known/openid-configuration
```

identity:

```
http://localhost:8082/identity/restv1/scim-configuration
```

Shibboleth (this will be xml data):

```
http://localhost:8086/idp/shibboleth
```

Passport(Just return a 200 and some data):

```
http://localhost:8090/passport
```

**Comment by mbaser** [comment]
commit c1f12df83d91d88fa46a0457373478938273f696 closed this issue
