### ISSUE TITLE
Protect openldap:1636 with stunnel

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#98]
Utilize the same method of protecting redis:6379 with openldap:1636, preventing external connection capability.

**Comment by tecoholic** [comment]
OpenLDAP on port 1636 already utilizes `ldaps` protocol and is secure. Using stunnel would be unnecessary.

**Comment by afroDC** [comment]
@tecoholic I want to make it impossible to attempt to connect to LDAP on port 1636. Stunnel would obfuscate that connection, only allowing proper SSL from a properly configured stunnel.

**Comment by afroDC** [comment]
We will just update the documentation with firewall instructions on proper network protection.
